ci:
  autofix_prs: false
  autoupdate_commit_msg: 'pre-commit: bump repositories'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-ast
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: double-quote-string-fixer
- repo: https://github.com/PyCQA/isort
  rev: 5.9.3
  hooks:
    - id: isort
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.19.0
  hooks:
  - id: setup-cfg-fmt
    args: ["--min-py3-version", "3.7", "--max-py-version", "3.9"]
- repo: https://github.com/PyCQA/flake8
  rev: "4.0.1"
  hooks:
  - id: flake8
    language_version: python3.9
